// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ZHLTGe1I6pZ6CU8kRE2N1xLjMM9VMzc',
    appId: '1:955110002675:web:5077e139e7d74dc4aa8c86',
    messagingSenderId: '955110002675',
    projectId: 'flutterwithfb-a7e42',
    authDomain: 'flutterwithfb-a7e42.firebaseapp.com',
    databaseURL: 'https://flutterwithfb-a7e42-default-rtdb.firebaseio.com',
    storageBucket: 'flutterwithfb-a7e42.appspot.com',
    measurementId: 'G-T6JEDHG1ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbpGvnTvpG7Dr49CcnXAsfWV2vJtIn9Q',
    appId: '1:955110002675:android:1c2adc5fde3d2f32aa8c86',
    messagingSenderId: '955110002675',
    projectId: 'flutterwithfb-a7e42',
    databaseURL: 'https://flutterwithfb-a7e42-default-rtdb.firebaseio.com',
    storageBucket: 'flutterwithfb-a7e42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2NnGpcPgNaLd2IB9jI_43v56boq3zXE',
    appId: '1:955110002675:ios:c259413c950d4cc4aa8c86',
    messagingSenderId: '955110002675',
    projectId: 'flutterwithfb-a7e42',
    databaseURL: 'https://flutterwithfb-a7e42-default-rtdb.firebaseio.com',
    storageBucket: 'flutterwithfb-a7e42.appspot.com',
    iosClientId: '955110002675-akdujnh9cgmfb8tbdp9surnm30eftqri.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2NnGpcPgNaLd2IB9jI_43v56boq3zXE',
    appId: '1:955110002675:ios:c259413c950d4cc4aa8c86',
    messagingSenderId: '955110002675',
    projectId: 'flutterwithfb-a7e42',
    databaseURL: 'https://flutterwithfb-a7e42-default-rtdb.firebaseio.com',
    storageBucket: 'flutterwithfb-a7e42.appspot.com',
    iosClientId: '955110002675-akdujnh9cgmfb8tbdp9surnm30eftqri.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );
}
